# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
